spring.application.name=TrueFilmsProject
spring.datasource.url=jdbc:postgresql://localhost:5432/photo_db
spring.datasource.username=alexis
spring.datasource.password=True

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true